#!/usr/bin/env python3
r"""Dot plot of a single permutation as a PNG (pure Python, no dependencies).

    python3 plot_perm.py PERM_FILE -o OUT_PREFIX [--cell PX] [--dot PX] [--tikz FILE]

PERM_FILE holds one permutation (values 1..n, space separated; further lines
are ignored).  The picture uses the orientation of heatmap.py: position i
increases from left to right and value increases from bottom to top, so the
letter pi_i is a dot in column i and row pi_i.  Each cell is `--cell` pixels
wide (default: about 900 pixels across) and the dot is a centred black
square of `--dot` pixels (default: half a cell, at least 3 pixels).  Writes
OUT_PREFIX.png and OUT_PREFIX.txt (the permutation on one line).

With --tikz FILE the permutation is also written as a TikZ picture for LaTeX:
the picture uses the lengths \permcell (cell size) and \permdot (dot
radius), which the including document must define, and its bounding box is
exactly n by n cells, so that it fits a box of width n * \permcell.  The
paper's Figure 2 includes such a file.
"""
import argparse
import os
import struct
import sys
import zlib

sys.path.insert(0, os.path.dirname(os.path.abspath(__file__)))
from heatmap import _png_chunk  # noqa: E402


def read_perm(path):
    with open(path) as f:
        for line in f:
            values = [int(tok) for tok in line.split()]
            if values:
                break
        else:
            raise SystemExit(f"{path}: no permutation found")
    n = len(values)
    if sorted(values) != list(range(1, n + 1)):
        raise SystemExit(f"{path}: first line is not a permutation of 1..n")
    return values


def write_dot_plot(path, perm, cell, dot, background=(255, 255, 255), ink=(0, 0, 0)):
    n = len(perm)
    width = height = n * cell
    margin = (cell - dot) // 2
    # image row r (0 = top) covers value n - r // cell
    rows_ink = {}
    for i, v in enumerate(perm):                # i: 0-based position, v: value
        x0 = i * cell + margin
        y0 = (n - v) * cell + margin           # top pixel row of the dot
        for y in range(y0, y0 + dot):
            rows_ink.setdefault(y, []).append(x0)
    blank = bytes(background) * width
    raw = bytearray()
    for y in range(height):
        raw.append(0)                           # PNG filter type 0
        if y in rows_ink:
            line = bytearray(blank)
            for x0 in rows_ink[y]:
                line[3 * x0:3 * (x0 + dot)] = bytes(ink) * dot
            raw.extend(line)
        else:
            raw.extend(blank)
    ihdr = struct.pack(">IIBBBBB", width, height, 8, 2, 0, 0, 0)
    with open(path, "wb") as f:
        f.write(b"\x89PNG\r\n\x1a\n")
        f.write(_png_chunk(b"IHDR", ihdr))
        f.write(_png_chunk(b"IDAT", zlib.compress(bytes(raw), 9)))
        f.write(_png_chunk(b"IEND", b""))
    return width, height


def write_tikz(path, perm, source):
    n = len(perm)
    pairs = [f"{i + 1}/{v}" for i, v in enumerate(perm)]
    lines, cur = [], "   "
    for pair in pairs:
        if len(cur) + len(pair) + 2 > 76:
            lines.append(cur)
            cur = "   "
        cur += " " + pair + ","
    lines.append(cur.rstrip(","))
    with open(path, "w") as f:
        f.write(f"% dot plot of one uniform random permutation in Av_{n}(12453);\n")
        f.write(f"% data: {source}; generated by code/av12453_sampler/plot_perm.py --tikz\n")
        f.write("\\begin{tikzpicture}[x=\\permcell,y=\\permcell]\n")
        f.write(f"  \\useasboundingbox (0.5,0.5) rectangle ({n}.5,{n}.5);\n")
        f.write(f"  \\draw[black!40,line width=0.3pt] (0.5,0.5) rectangle ({n}.5,{n}.5);\n")
        f.write("  \\foreach \\i/\\v in {%\n" + "\n".join(lines) + "}\n")
        f.write("    \\fill (\\i,\\v) circle[radius=\\permdot];\n")
        f.write("\\end{tikzpicture}%\n")


def main(argv=None):
    ap = argparse.ArgumentParser(description=__doc__.split("\n\n")[0])
    ap.add_argument("perm_file")
    ap.add_argument("-o", "--out", required=True, help="output path prefix")
    ap.add_argument("--cell", type=int, default=None, help="pixels per position/value (default: ~900 px image)")
    ap.add_argument("--dot", type=int, default=None, help="dot side in pixels (default: max(3, cell // 2))")
    ap.add_argument("--tikz", default=None, metavar="FILE", help="also write the permutation as a TikZ picture")
    args = ap.parse_args(argv)
    perm = read_perm(args.perm_file)
    n = len(perm)
    cell = args.cell or max(3, 900 // n)
    dot = args.dot or max(3, cell // 2)
    if dot > cell:
        raise SystemExit("--dot must not exceed --cell")
    w, h = write_dot_plot(args.out + ".png", perm, cell, dot)
    with open(args.out + ".txt", "w") as f:
        f.write(" ".join(map(str, perm)) + "\n")
    print(f"n={n} cell={cell} dot={dot} -> {args.out}.png ({w}x{h}), {args.out}.txt")
    if args.tikz:
        write_tikz(args.tikz, perm, os.path.relpath(args.perm_file, os.path.join(os.path.dirname(os.path.abspath(__file__)), "..", "..")))
        print(f"TikZ picture -> {args.tikz}")


if __name__ == "__main__":
    main()
