/-
Copyright (c) 2026 Henning Ulfarsson. All rights reserved.
Released under Apache 2.0 license as described in the file LICENSE.
Authors: Henning Ulfarsson
-/
module

public import PermPatterns.Perm
public import PermPatterns.Sums

@[expose] public section

/-!
# The three symmetries of a permutation class

The symmetries of the square act on permutations; they are generated by the *reverse*
(`List.reverse`, reflection in a vertical axis), the *complement* (`PermPatterns.complement`,
reflection in a horizontal axis) and the *inverse* (`PermPatterns.inverse`, reflection in the
main diagonal).  Each of them transports containment, hence each induces a bijection between
`Av(B)` and `Av(B')` for the correspondingly transformed basis `B'`: the classical *Wilf
equivalences by symmetry*.

## Main definitions

* `PermPatterns.complement` : the complement `w ↦ (n-1-w_0) ⋯ (n-1-w_{n-1})` of a word on
  the values `{0, …, n-1}`.
* `PermPatterns.inverse` : the inverse of a word that is a permutation, given by
  `List.idxOf` and so computable.
* `PermPatterns.permReverse`, `PermPatterns.permComplement` : the reverse `σ ∘ rev` and the
  complement `rev ∘ σ` on `Equiv.Perm (Fin n)`; the inverse there is the group inverse `σ⁻¹`.

## Main results

* `PermPatterns.contains_reverse_iff`, `PermPatterns.contains_complement_iff`,
  `PermPatterns.contains_inverse_iff` : the three containment transports on words.
* `PermPatterns.permContains_inv_iff` : the inverse transport on `Equiv.Perm (Fin n)`, where
  it is natural; `PermPatterns.contains_inverse_iff` is its word form.
* `PermPatterns.card_avoiders_reverse`, `PermPatterns.card_avoiders_complement`,
  `PermPatterns.card_avoiders_inverse` : the three Wilf equivalences by symmetry.
* `PermPatterns.complement_directSum` : the complement exchanges the direct and the skew sum.
-/

namespace PermPatterns

open List

variable {n k : ℕ} {w v τ α β : List ℕ}

/-! ### Reversal -/

/-- Reversing a word and its pattern transports containment. -/
theorem Contains.reverse (h : Contains w τ) : Contains w.reverse τ.reverse := by
  obtain ⟨s, hs, hiso⟩ := h
  exact ⟨s.reverse, hs.reverse, hiso.reverse⟩

/-- **Reverse symmetry.**  A word contains a pattern exactly when the reversed word contains
the reversed pattern. -/
theorem contains_reverse_iff : Contains w.reverse τ.reverse ↔ Contains w τ := by
  refine ⟨fun h => ?_, Contains.reverse⟩
  simpa using h.reverse

/-- The reverse of a permutation of `{0, …, n-1}` is again one. -/
theorem reverse_isPermOf (h : IsPermOf n w) : IsPermOf n w.reverse :=
  (List.reverse_perm w).trans h

/-! ### Complement -/

/--
The *complement* of a word on the values `{0, …, n-1}` : every letter `x` is replaced by
`n - 1 - x`, so that the word is reflected in a horizontal axis.
-/
def complement (n : ℕ) (w : List ℕ) : List ℕ := w.map fun x => n - 1 - x

/-- The complement has the same length as the word. -/
@[simp] theorem length_complement : (complement n w).length = w.length := by
  simp [complement]

/-- The letter of `complement n w` at position `i` is `n - 1 - w[i]`. -/
@[simp] theorem getElem_complement {i : ℕ} (hi : i < (complement n w).length) :
    (complement n w)[i] = n - 1 - w[i]'(by simpa using hi) := by
  simp [complement]

/-- The letters of a complement. -/
theorem mem_complement {z : ℕ} : z ∈ complement n w ↔ ∃ x ∈ w, n - 1 - x = z := by
  simp [complement]

/-- The complement of a word with values below `n` again has values below `n`. -/
theorem complement_lt (hw : ∀ x ∈ w, x < n) : ∀ z ∈ complement n w, z < n := by
  intro z hz
  obtain ⟨x, hx, rfl⟩ := mem_complement.mp hz
  have := hw x hx
  omega

/-- The complement is an involution on words with values below `n`. -/
theorem complement_complement (hw : ∀ x ∈ w, x < n) : complement n (complement n w) = w := by
  simp only [complement, List.map_map]
  refine (List.map_congr_left fun x hx => ?_).trans (List.map_id w)
  have := hw x hx
  simp only [Function.comp_apply, id_eq]
  omega

/-- The complement of a permutation of `{0, …, n-1}` is again one. -/
theorem complement_isPermOf (h : IsPermOf n w) : IsPermOf n (complement n w) := by
  have hlt : ∀ x ∈ w, x < n := fun x hx => h.lt_of_mem hx
  refine isPermOf_iff.mpr ⟨?_, by simp [h.length], complement_lt hlt⟩
  refine List.Nodup.map_on (fun x hx y hy hxy => ?_) h.nodup
  have := hlt x hx
  have := hlt y hy
  omega

/-- The complement reverses every comparison, so it preserves order isomorphism. -/
theorem OrderIsomorphic.complement {m : ℕ} (h : OrderIsomorphic w v) (hw : ∀ x ∈ w, x < n)
    (hv : ∀ x ∈ v, x < m) :
    OrderIsomorphic (PermPatterns.complement n w) (PermPatterns.complement m v) := by
  refine ⟨by simp [h.length_eq], fun i j hi hj hi' hj' => ?_⟩
  simp only [length_complement] at hi hj hi' hj'
  rw [getElem_complement, getElem_complement, getElem_complement, getElem_complement]
  have h1 := hw _ (List.getElem_mem hi)
  have h2 := hw _ (List.getElem_mem hj)
  have h3 := hv _ (List.getElem_mem hi')
  have h4 := hv _ (List.getElem_mem hj')
  have hji := h.lt_iff hj hi hj' hi'
  omega

/-- Complementing a word and its pattern transports containment. -/
theorem Contains.complement (h : Contains w τ) (hw : ∀ x ∈ w, x < n) (hτ : ∀ x ∈ τ, x < k) :
    Contains (PermPatterns.complement n w) (PermPatterns.complement k τ) := by
  obtain ⟨s, hs, hiso⟩ := h
  exact ⟨PermPatterns.complement n s, hs.map _,
    hiso.complement (fun x hx => hw x (hs.subset hx)) hτ⟩

/-- **Complement symmetry.**  A word on `{0, …, n-1}` contains a pattern on `{0, …, k-1}`
exactly when the complemented word contains the complemented pattern. -/
theorem contains_complement_iff (hw : ∀ x ∈ w, x < n) (hτ : ∀ x ∈ τ, x < k) :
    Contains (complement n w) (complement k τ) ↔ Contains w τ := by
  refine ⟨fun h => ?_, fun h => h.complement hw hτ⟩
  have hc := h.complement (complement_lt hw) (complement_lt hτ)
  rwa [complement_complement hw, complement_complement hτ] at hc

/-! ### The symmetries on `Equiv.Perm (Fin n)` -/

/-- The *reverse* of a permutation of `Fin n`: the letters are read from the right. -/
def permReverse {n : ℕ} (σ : Equiv.Perm (Fin n)) : Equiv.Perm (Fin n) := σ * Fin.revPerm

/-- The *complement* of a permutation of `Fin n`: every value is replaced by its reverse. -/
def permComplement {n : ℕ} (σ : Equiv.Perm (Fin n)) : Equiv.Perm (Fin n) := Fin.revPerm * σ

/-- The reverse of `σ` sends `i` to `σ i.rev`. -/
@[simp] theorem permReverse_apply {n : ℕ} (σ : Equiv.Perm (Fin n)) (i : Fin n) :
    permReverse σ i = σ i.rev := rfl

/-- The complement of `σ` sends `i` to `(σ i).rev`. -/
@[simp] theorem permComplement_apply {n : ℕ} (σ : Equiv.Perm (Fin n)) (i : Fin n) :
    permComplement σ i = (σ i).rev := rfl

/-- The word of the reverse of a permutation is the reverse of its word. -/
theorem ofPerm_permReverse {n : ℕ} (σ : Equiv.Perm (Fin n)) :
    ofPerm (permReverse σ) = (ofPerm σ).reverse := by
  refine List.ext_getElem (by simp) fun i hi hi' => ?_
  rw [getElem_ofPerm, List.getElem_reverse, getElem_ofPerm, permReverse_apply]
  refine congrArg (fun t : Fin n => ((σ t : Fin n) : ℕ)) (Fin.ext ?_)
  simp only [Fin.val_rev, length_ofPerm]
  omega

/-- The word of the complement of a permutation is the complement of its word. -/
theorem ofPerm_permComplement {n : ℕ} (σ : Equiv.Perm (Fin n)) :
    ofPerm (permComplement σ) = complement n (ofPerm σ) := by
  refine List.ext_getElem (by simp) fun i hi hi' => ?_
  rw [getElem_ofPerm, getElem_complement, getElem_ofPerm, permComplement_apply, Fin.val_rev]
  omega

/-- **Reverse symmetry** on `Equiv.Perm (Fin n)`. -/
theorem permContains_permReverse_iff {n k : ℕ} {σ : Equiv.Perm (Fin n)}
    {τ : Equiv.Perm (Fin k)} :
    PermContains (permReverse σ) (permReverse τ) ↔ PermContains σ τ := by
  rw [permContains_iff_contains, permContains_iff_contains, ofPerm_permReverse,
    ofPerm_permReverse, contains_reverse_iff]

/-- **Complement symmetry** on `Equiv.Perm (Fin n)`. -/
theorem permContains_permComplement_iff {n k : ℕ} {σ : Equiv.Perm (Fin n)}
    {τ : Equiv.Perm (Fin k)} :
    PermContains (permComplement σ) (permComplement τ) ↔ PermContains σ τ := by
  rw [permContains_iff_contains, permContains_iff_contains, ofPerm_permComplement,
    ofPerm_permComplement,
    contains_complement_iff (fun _ hx => (ofPerm_isPermOf σ).lt_of_mem hx)
      (fun _ hx => (ofPerm_isPermOf τ).lt_of_mem hx),
    ← permContains_iff_contains]

/-- Inverting a permutation and its pattern transports containment: if `f` embeds the
positions of `τ` in those of `σ`, then `σ ∘ f ∘ τ⁻¹` embeds the positions of `τ⁻¹` in those
of `σ⁻¹`. -/
theorem PermContains.inv {n k : ℕ} {σ : Equiv.Perm (Fin n)} {τ : Equiv.Perm (Fin k)}
    (h : PermContains σ τ) : PermContains σ⁻¹ τ⁻¹ := by
  obtain ⟨f, hf⟩ := h
  have hmono : StrictMono fun a : Fin k => σ (f (τ⁻¹ a)) := by
    intro a b hab
    exact (hf (τ⁻¹ a) (τ⁻¹ b)).mp (by simpa using hab)
  refine ⟨OrderEmbedding.ofStrictMono _ hmono, fun i j => ?_⟩
  simp only [OrderEmbedding.coe_ofStrictMono, Equiv.Perm.inv_def, Equiv.symm_apply_apply]
  exact f.lt_iff_lt.symm

/-- **Inverse symmetry** on `Equiv.Perm (Fin n)`, where it is natural. -/
theorem permContains_inv_iff {n k : ℕ} {σ : Equiv.Perm (Fin n)} {τ : Equiv.Perm (Fin k)} :
    PermContains σ⁻¹ τ⁻¹ ↔ PermContains σ τ :=
  ⟨fun h => by simpa using h.inv, PermContains.inv⟩

/-! ### The inverse of a word -/

/--
The *inverse* of a word that is a permutation of `{0, …, n-1}` : its `i`-th letter is the
position of the value `i`.  Written with `List.idxOf`, so no permutation hypothesis is
needed to state it and the definition is computable;
`PermPatterns.inverse_eq_ofPerm` identifies it with the group inverse of
`PermPatterns.toPerm`.
-/
def inverse (w : List ℕ) : List ℕ := (List.range w.length).map fun x => w.idxOf x

/-- The inverse has the same length as the word. -/
@[simp] theorem length_inverse : (inverse w).length = w.length := by simp [inverse]

/-- The letter of `inverse w` at position `i` is the position of the value `i` in `w`. -/
@[simp] theorem getElem_inverse {i : ℕ} (hi : i < (inverse w).length) :
    (inverse w)[i] = w.idxOf i := by
  simp [inverse]

/-- The inverse of a word is the word of the inverse permutation. -/
theorem inverse_eq_ofPerm (h : IsPermOf n w) : inverse w = ofPerm (toPerm w h)⁻¹ := by
  rw [Equiv.Perm.inv_def]
  refine List.ext_getElem (by simp [h.length]) fun i hi hi' => ?_
  rw [getElem_inverse, getElem_ofPerm, toPerm_symm_apply]

/-- The inverse of a permutation of `{0, …, n-1}` is again one. -/
theorem inverse_isPermOf (h : IsPermOf n w) : IsPermOf n (inverse w) := by
  rw [inverse_eq_ofPerm h]
  exact ofPerm_isPermOf _

/-- The permutation of the inverse of a word is the inverse of its permutation. -/
theorem toPerm_inverse (h : IsPermOf n w) (h' : IsPermOf n (inverse w)) :
    toPerm (inverse w) h' = (toPerm w h)⁻¹ := by
  rw [Equiv.Perm.inv_def]
  refine Equiv.ext fun i => Fin.ext ?_
  rw [toPerm_apply, getElem_inverse, toPerm_symm_apply]

/-- The inverse is an involution on permutations of `{0, …, n-1}`. -/
theorem inverse_inverse (h : IsPermOf n w) : inverse (inverse w) = w := by
  rw [inverse_eq_ofPerm (inverse_isPermOf h), toPerm_inverse h (inverse_isPermOf h), inv_inv,
    ofPerm_toPerm]

/-- **Inverse symmetry** on words: this is `PermPatterns.permContains_inv_iff` read through
the bridge. -/
theorem contains_inverse_iff (hw : IsPermOf n w) (hτ : IsPermOf k τ) :
    Contains (inverse w) (inverse τ) ↔ Contains w τ := by
  rw [inverse_eq_ofPerm hw, inverse_eq_ofPerm hτ, ← permContains_iff_contains,
    permContains_inv_iff, permContains_iff_contains, ofPerm_toPerm, ofPerm_toPerm]

/-! ### Wilf equivalence by symmetry -/

/-- **Reverse Wilf equivalence.**  Reversing every pattern of the basis does not change the
number of avoiders. -/
theorem card_avoiders_reverse (n : ℕ) (B : Finset (List ℕ)) :
    (avoiders n (B.image List.reverse)).card = (avoiders n B).card := by
  refine Finset.card_bij' (fun v _ => v.reverse) (fun v _ => v.reverse) ?_ ?_ ?_ ?_
  · intro v hv
    rw [mem_avoiders] at hv ⊢
    refine ⟨reverse_isPermOf hv.1, fun σ hσ => ?_⟩
    have h0 := contains_reverse_iff (w := v) (τ := σ.reverse)
    rw [List.reverse_reverse] at h0
    exact fun hc => hv.2 _ (Finset.mem_image_of_mem List.reverse hσ) (h0.mp hc)
  · intro v hv
    rw [mem_avoiders] at hv ⊢
    refine ⟨reverse_isPermOf hv.1, fun σ hσ => ?_⟩
    obtain ⟨σ', hσ', rfl⟩ := Finset.mem_image.mp hσ
    exact fun hc => hv.2 σ' hσ' (contains_reverse_iff.mp hc)
  · exact fun v _ => List.reverse_reverse v
  · exact fun v _ => List.reverse_reverse v

/-- **Complement Wilf equivalence.**  Complementing every pattern of the basis in its own
length does not change the number of avoiders. -/
theorem card_avoiders_complement (n : ℕ) (B : Finset (List ℕ))
    (hB : ∀ τ ∈ B, IsPermOf τ.length τ) :
    (avoiders n (B.image fun τ => complement τ.length τ)).card = (avoiders n B).card := by
  refine Finset.card_bij' (fun v _ => complement n v) (fun v _ => complement n v) ?_ ?_ ?_ ?_
  · intro v hv
    rw [mem_avoiders] at hv ⊢
    have hvlt : ∀ x ∈ v, x < n := fun x hx => hv.1.lt_of_mem hx
    refine ⟨complement_isPermOf hv.1, fun σ hσ => ?_⟩
    have hσn : ∀ x ∈ σ, x < σ.length := fun x hx => (hB σ hσ).lt_of_mem hx
    have h0 := contains_complement_iff (n := n) (k := σ.length) (w := complement n v)
      (τ := σ) (complement_lt hvlt) hσn
    rw [complement_complement hvlt] at h0
    exact fun hc => hv.2 _ (Finset.mem_image_of_mem _ hσ) (h0.mpr hc)
  · intro v hv
    rw [mem_avoiders] at hv ⊢
    have hvlt : ∀ x ∈ v, x < n := fun x hx => hv.1.lt_of_mem hx
    refine ⟨complement_isPermOf hv.1, fun σ hσ => ?_⟩
    obtain ⟨σ', hσ', rfl⟩ := Finset.mem_image.mp hσ
    have hσn : ∀ x ∈ σ', x < σ'.length := fun x hx => (hB σ' hσ').lt_of_mem hx
    exact fun hc => hv.2 σ' hσ'
      ((contains_complement_iff (n := n) (k := σ'.length) hvlt hσn).mp hc)
  · exact fun v hv => complement_complement fun x hx => (mem_avoiders.mp hv).1.lt_of_mem hx
  · exact fun v hv => complement_complement fun x hx => (mem_avoiders.mp hv).1.lt_of_mem hx

/-- **Inverse Wilf equivalence.**  Inverting every pattern of the basis does not change the
number of avoiders. -/
theorem card_avoiders_inverse (n : ℕ) (B : Finset (List ℕ))
    (hB : ∀ τ ∈ B, IsPermOf τ.length τ) :
    (avoiders n (B.image inverse)).card = (avoiders n B).card := by
  refine Finset.card_bij' (fun v _ => inverse v) (fun v _ => inverse v) ?_ ?_ ?_ ?_
  · intro v hv
    rw [mem_avoiders] at hv ⊢
    refine ⟨inverse_isPermOf hv.1, fun σ hσ => ?_⟩
    have h0 := contains_inverse_iff (n := n) (k := σ.length) (w := inverse v) (τ := σ)
      (inverse_isPermOf hv.1) (hB σ hσ)
    rw [inverse_inverse hv.1] at h0
    exact fun hc => hv.2 _ (Finset.mem_image_of_mem inverse hσ) (h0.mpr hc)
  · intro v hv
    rw [mem_avoiders] at hv ⊢
    refine ⟨inverse_isPermOf hv.1, fun σ hσ => ?_⟩
    obtain ⟨σ', hσ', rfl⟩ := Finset.mem_image.mp hσ
    exact fun hc => hv.2 σ' hσ' ((contains_inverse_iff hv.1 (hB σ' hσ')).mp hc)
  · exact fun v hv => inverse_inverse (mem_avoiders.mp hv).1
  · exact fun v hv => inverse_inverse (mem_avoiders.mp hv).1

/-! ### The complement and the two sums -/

/-- The complement exchanges the direct and the skew sum. -/
theorem complement_directSum (hα : ∀ x ∈ α, x < α.length) :
    complement (α.length + β.length) (directSum α β) =
      skewSum (complement α.length α) (complement β.length β) := by
  simp only [complement, directSum, skewSum, List.map_append, List.map_map, List.length_map]
  refine congrArg₂ (· ++ ·) (List.map_congr_left fun x hx => ?_)
    (List.map_congr_left fun y _ => ?_)
  · have := hα x hx
    simp only [Function.comp_apply]
    omega
  · simp only [Function.comp_apply]
    omega

/-! ### Sanity checks -/

/-- The reverse of `1342` (`0`-based `[0, 2, 3, 1]`) is `2431` (`0`-based `[1, 3, 2, 0]`). -/
example : ([0, 2, 3, 1] : List ℕ).reverse = [1, 3, 2, 0] := by decide

/-- The complement of `1342` is `4213` (`0`-based `[3, 1, 0, 2]`). -/
example : complement 4 [0, 2, 3, 1] = [3, 1, 0, 2] := by decide

/-- The inverse of `1342` is `1423` (`0`-based `[0, 3, 1, 2]`). -/
example : inverse [0, 2, 3, 1] = [0, 3, 1, 2] := by decide

/-- `(1 ⊕ 231)ᶜ = 1ᶜ ⊖ 231ᶜ`, i.e. `1342ᶜ = 4213 = 1 ⊖ 213`. -/
example : complement 4 (directSum [0] [1, 2, 0]) = skewSum (complement 1 [0])
    (complement 3 [1, 2, 0]) := by decide

end PermPatterns
